zxsite/bodypage/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
#----------------------------------------------分割线--------------------------------------------------
    #主页
    url(r'^index/$',views.index,name='index'),
#----------------------------------------------分割线--------------------------------------------------
    #用户注册登录等
    url(r'^login/$',views.log_in,name='login'),
    url(r'^login/validatename/$',views.validatename),
    url(r'^login/validatepw/$',views.validatepw),
    url(r'^logout/$',views.log_out,name='logout'),
    url(r'^register/$',views.register,name='register'),
    url(r'^register/verifyname',views.verifyname,name='verifyname'),

#----------------------------------------------分割线--------------------------------------------------
    #用户信息
    url(r'^user/(?P<user_id>[0-9]+)/$',views.userpage,name='userpage'),
    url(r'^user/settings/(?P<user_id>[0-9]+)/$',views.edit_user_info,name='edit_user_info'),
    #用户管理文章
    url(r'^user/article-manage/(?P<user_id>[0-9]+)/$',views.article_manage,name='article_manage'),
    url(r'^user/article-manage/edit/(?P<article_id>[0-9]+)/$',views.article_edit,name='article_edit'),
    url(r'^user/article-manage/newarticle/(?P<user_id>[0-9]+)/$',views.new_article,name='new_article'),
    url(r'^user/article-manage/draftarticle/(?P<user_id>[0-9]+)/$',views.draftarticle,name='draftarticle'),
    url(r'^user/article-manage/delete/(?P<user_id>[0-9]+)/$',views.d_article,name='d_aticle'),
    #用户删除文章
    url(r'^user/delete-article/(?P<article_id>[0-9]+)/$',views.delete_article,name='delete_article'),
    #用户关注
    url(r'user/addlikes/(?P<user_id>[0-9]+)/$',views.addlikes,name='addlikes'),
    #彻底删除文章以及还原文章
    url(r'^delete-completly/(?P<article_id>[0-9]+)/$',views.delete_compeletly,name='deletecompletly'),
    url(r'^delete-back/(?P<article_id>[0-9]+)/$',views.delete_back,name='deleteback'),

#----------------------------------------------分割线--------------------------------------------------
    #文章信息
    url(r'^article/(?P<article_id>[0-9]+)/$',views.article_ins,name='article_ins'),
    #文章评论信息
    url(r'^article/comments/(?P<article_id>[0-9]+)/$',views.article_ins_comment,name='article_ins_comments'),
    #文章点赞
    url(r'^articles/likes/(?P<article_id>[0-9]+)/$',views.handle_like),


#----------------------------------------------分割线--------------------------------------------------
    #TAG相关
    url(r'^tag/articles/(?P<tag_id>[0-9]+)/$',views.tag_article,name='tag_article'),
#----------------------------------------------分割线--------------------------------------------------
    #test
    url(r'test/(?P<user_id>[0-9]+)/$',views.testpage,name='testpage'),
    url(r'test/testload/$',views.testload),
#----------------------------------------------分割线--------------------------------------------------
    #搜索功能
    url(r'search/$',views.search,name='search')

]

zxsite/zxsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^',include('bodypage.urls',namespace='bodypage',app_name='bodypage')),
    url(r'^admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zxsite/bodypage/models.py
from django.db import models
from django.contrib.auth.models import User

#用户数据库，作为user的附加
class Bloger(models.Model):
    user = models.OneToOneField(User)
    likelist = models.ManyToManyField('Bloger',verbose_name='关注列表',null=True,blank=True,related_name='re_likelists')
    nickname = models.CharField(max_length=20,null=True,blank=True)
    age = models.PositiveIntegerField(default=0)
    portrait = models.ImageField('头像',upload_to='pic/' ,default='pic/timg.jpg')
    GENDER_CHOICE = (
        ('F','FEMALE'),
        ('M','MALE')
    )
    gender = models.CharField(max_length=5,choices=GENDER_CHOICE)
    signiture = models.CharField(max_length=100)
    address = models.CharField(max_length=10)
    def __str__(self):
        return self.user.username


#文章信息
class Article(models.Model):
    author = models.ForeignKey('Bloger',verbose_name='作者')
    tags = models.ManyToManyField('Tag',verbose_name='标签')
    title = models.CharField('标题',max_length=50)
    content = models.TextField('正文')
    abstract = models.CharField('摘要',max_length=50)
    ARTICLE_STATUS = (
        ('P','PUBLIC'),
        ('E','EDITING'),
        ('D','DELETED'),
        ('C','DELETE-COMPELETLY')
    )
    status = models.CharField('文章状态',max_length=1,choices=ARTICLE_STATUS)
    created_time = models.DateTimeField('创建时间',auto_now_add=True)
    lasted_modified_time = models.DateTimeField('最新修改时间',auto_now=True)
    views = models.PositiveIntegerField('浏览数',default=0)
    likes = models.PositiveIntegerField('点赞数',default=0)
    topped = models.BooleanField('是否置顶',default=False)

    def __str__(self):
        return self.title
    #按修改时间排列
    class meta:
        ordering = ['-lasted_modified_time']

#文章标签
class Tag(models.Model):
    name = models.CharField('标签名',max_length=10)
    TAG_STATUS = (
        ('P','PUBLIC'),
        ('D','DELETE')
    )
    status = models.CharField(max_length=1,choices=TAG_STATUS)
    created_time = models.DateTimeField('创建时间',auto_now_add=True)
    related_articles = models.PositiveIntegerField('相关文章数')
    def __str__(self):
        return self.name
    class meta:
        ordering = ['-related_articles']

#评论
class Comment(models.Model):
    article = models.ForeignKey('Article',verbose_name='对应文章')
    author = models.ForeignKey('Bloger',verbose_name='作者')
    content = models.TextField('评论内容')
    TAG_STATUS = (
        ('P', 'PUBLIC'),
        ('D', 'DELETE')
    )
    status = models.CharField(max_length=1, choices=TAG_STATUS)
    created_time = models.DateTimeField(auto_now_add=True)
    likes = models.PositiveIntegerField(default=0)
    topped = models.BooleanField('是否置顶',default=False)


    def __str__(self):
        return self.content

#子评论
class Subcomment(models.Model):
    parent_comment = models.ForeignKey('Comment',verbose_name='评论')
    author = models.ForeignKey('Bloger',verbose_name='作者')
    content = models.TextField('评论内容')
    TAG_STATUS = (
        ('P', 'PUBLIC'),
        ('D', 'DELETE')
    )
    status = models.CharField(max_length=1, choices=TAG_STATUS)
    created_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

zxsite/bodypage/forms.py
from django import forms

class Portrait(forms.Form):
    porfile = forms.ImageField()

zxsite/bodypage/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import logout,login,authenticate
from .models import Article,Bloger,Comment,Tag,Subcomment
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .forms import Portrait
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from PIL import Image
import json
from django.core import serializers
#----------------------------------------------分割线--------------------------------------------------
#主页视图函数
def index(request):
    articles = Article.objects.filter(status='P')
    tags = Tag.objects.order_by('related_articles')
    content = {
        'articles':articles,
        'tags':tags
    }
    return render(request,'bodypage/index.html',content)
#----------------------------------------------分割线--------------------------------------------------
#注册页处理函数
def register(request):
    if request.method == 'POST':
        #解包，获得3个值
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        #添加错误处理
        error = ''
        #检查重名
        name_check = User.objects.filter(username=username)
        if len(name_check) == 0:
            #检查密码是否相等
            if password1 == password2:
                ins_user = User.objects.create_user(
                    username = username,
                    password = password1
                )
                Bloger.objects.create(
                    user = ins_user
                )
                newuser = authenticate(username=username,password=password1)
                login(request,newuser)
                return redirect('/index')
            else:
                error = '密码重复，请重新注册'
                content = {
                    'errors':error
                }
                return render(request,'bodypage/register.html',content)
        else:
            error = '已存在相同用户名，请重新注册'
            content = {
                'errors':error
            }
            return render(request,'bodypage/register.html',content)

    else:
        return render(request, 'bodypage/register.html')
#----------------------------------------------分割线-------------------------------------------------
def verifyname(request):
    if request.method == 'POST':
        username = request.POST.get('name')
        ###############################
        # try:
        #     result = User.objects.get(username__exact=username)
        #     result = serializers.serialize('json', [result])
        #     content = {
        #             'data': result
        #         }
        # except:
        #     content = {
        #             'data':'T'
        #         }
        result = User.objects.filter(username__exact=username)
        if len(result) == 0:
            content = {
                'data':'T'
            }
        else:
            # result = serializers.serialize('json',result)
            # print(result)
            # print(type(result))
            content = {
                'data': 'F'
            }
    # return JsonResponse(content)
    return HttpResponse(json.dumps(content), content_type='application/json')
#----------------------------------------------分割线-------------------------------------------------
#登录处理函数
def log_in(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user =authenticate(username=username,password=password)
        if user and user.is_active:
            login(request,user)
            return redirect('/index')
        else:
            error = '用户不存在或者用户状态异常，请重新登录'
            content = {
                'errors':error
            }
            return render(request,'bodypage/login.html',content)
    else:
        return render(request,'bodypage/login.html')
# ----------------------------------------------分割线--------------------------------------------------
def validatename(request):
    if request.method == 'GET':
        print(request.GET)
        username = request.GET.get('username')
        result = User.objects.filter(username__exact=username)
        if len(result):
            content = {
                'judge':'T'
            }
        else:
            content = {
                'judge':'F'
            }
        return JsonResponse(content)
# ----------------------------------------------分割线--------------------------------------------------
def validatepw(request):
    if request.method == 'POST':
        print(request.POST)
        username = request.POST.get('username')
        result = User.objects.filter(username__exact=username)
        print(result)
        pw = request.POST.get('password')
        print(pw)
        user = authenticate(username=username, password=pw)
        print(user)
        if user and user.is_active:
            content = {
                'judge' : 'T'
            }
        else:
            content = {
                'judge' : 'F'
            }
        return JsonResponse(content)
#----------------------------------------------分割线--------------------------------------------------
#注销处理函数
def log_out(request):
    logout(request)
    return redirect('/index')
#----------------------------------------------分割线--------------------------------------------------
#用户主页函数
def userpage(request,user_id):
    user_info = User.objects.get(id=user_id)
    user_info_profile = Bloger.objects.get(user=user_info)
    user_article = Article.objects.filter(author=user_info_profile).filter(status='P')
    user_comments = Comment.objects.filter(author=user_info_profile)
    user_subcomments = Subcomment.objects.filter(author=user_info_profile)
    paginator = Paginator(user_article,4)
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        contacts = paginator.page(1)
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)
    content = {
        'user_info': user_info,
        'user_info_profile': user_info_profile,
        'user_article': contacts,
        'user_comments': user_comments,
        'user_subcomments': user_subcomments,
        'current_userid': int(user_id)
    }
    return render(request,'bodypage/user.html',content)

#----------------------------------------------分割线--------------------------------------------------
#用户管理文章页面
def article_manage(request,user_id):
    user_ins = User.objects.get(id=user_id)
    user_ins_profile = Bloger.objects.get(user=user_ins)
    user_article = Article.objects.filter(author=user_ins_profile)
    user_article_P = user_article.filter(status='P')
    user_article_E = user_article.filter(status='E')
    user_article_D = user_article.filter(status='D')
    content = {
        'user_ins':user_ins,
        'user_ins_profile':user_ins_profile,
        'user_article_P':user_article_P,
        'user_article_E': user_article_E,
        'user_article_D': user_article_D,
    }
    return render(request,'bodypage/article_manage.html',content)



# ----------------------------------------------分割线--------------------------------------------------
#用户编辑自己的文章
def article_edit(request,article_id):
    if request.method == 'POST':
        print(request.POST)
        article = Article.objects.get(id=article_id)

        bloger = Bloger.objects.get(id = article.author_id)

        #user_id =request.POST.get('user_id')
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.status = request.POST.get('status')
        article.abstract = article.content[:15]
        article.save()
        return redirect('/user/article-manage/%s' %(bloger.user_id))

    else:
        article_instance = Article.objects.get(id=article_id)

        content = {
            'article_instance':article_instance
        }
        return render(request,'bodypage/edit-article.html',content)

# ----------------------------------------------分割线--------------------------------------------------
#用户删除文章
def delete_article(request,article_id):
    if request.method == 'POST':
        print('s1')
        user_id = request.POST.get('user_id')
        article_instance = Article.objects.get(id=article_id)
        article_instance.status = 'D'
        article_instance.save()
        print('success2')
        return redirect('/user/article-manage/%s'%user_id)
# ----------------------------------------------分割线--------------------------------------------------
#用户关注用户
def addlikes(request,user_id):
    if request.method == 'POST':
        add_user_id = request.POST.get('userid')
        bloger_ins = Bloger.objects.get(user_id=user_id)
        add_bloger_ins = Bloger.objects.get(user_id=add_user_id)
        bloger_ins.likelist.add(add_bloger_ins)
        bloger_ins.save()
        return redirect('/user/%s'%(add_user_id))
    else:
        return redirect('/user/%s'%(user_id))


# ----------------------------------------------分割线--------------------------------------------------
#用户文章回收站
def d_article(request,user_id):
    user_ins = User.objects.get(id=user_id)
    bloger_ins = Bloger.objects.get(user=user_ins)
    article_d = Article.objects.filter(author=bloger_ins).filter(status='D')
    print(article_d)
    content = {
        'articles':article_d
    }
    return render(request,'bodypage/delete_article.html',content)
    # ----------------------------------------------分割线----------------------------------------------
#在回收站下还原文章
def delete_back(request,article_id):
    user_id = request.POST.get('user_id')
    article = Article.objects.get(id = article_id)
    article.status = 'P'
    article.save()
    return redirect('/user/article-manage/delete/%s'%(user_id))

    # ----------------------------------------------分割线----------------------------------------------
#在回收站下彻底删除文章

zxsite/bodypage/templates/bodypage/article_ins.html
{% extends 'bodypage/base-s2.html' %}

{% block article_ins-10 %}
    <!----------点赞------------>
    <div class="container-fluid" style="margin-left: 20px">
{#        <form method="post" action="/article/likes/{{ article_instance.id }}">#}
{#        {% csrf_token %}#}
{#            <input type="hidden" name="user_id" value="{{ user.id }}">#}

            <button type="submit" value="点赞" class="btn btn-default" style="margin-top: 200px;position: fixed" id="li_btn">
                <span class="glyphicon glyphicon-star" style="color: red "></span>
            </button>

{#        </form>#}

        <br>

    <button class="btn btn-info" data-toggle="modal" data-target="#mymodal" style="margin-top: 250px; position: fixed">评论</button>
    </div>


    <!----------评论按钮------------>


{% endblock %}



{% block article_ins-70 %}
<div class="container-fluid">
   <!----------------------------------正文-----------start------------------------------>
    <div class="h1">
        {{ article_instance.title }}
    </div>

    <hr>

    <div>
        <ul class="list-group list-inline">
            <li class="list-group-item">创建于：{{ article_instance.created_time }}</li>
            <li class="list-group-item">作者：{{ article_instance.author }}</li>
            <li class="list-group-item">浏览量：{{ article_instance.views }}</li>
            <li class="list-group-item" id="li_sum">热度：{{ article_instance.likes }}</li>
        </ul>
    </div>

    <!---文章标签--->
    <div class="btn-group-sm">
        <botton class="btn btn-default disabled"> 文章标签：</botton>
        {% for tag in article_instance.tags.all %}

            <a href="/tag/articles/{{ tag.id }}" ><button class="btn btn-success btn-sm">{{ tag }}</button></a>
        {% endfor %}
    </div>

    <br>

    <!---文章正文---->
    <div class="text-justify" style="text-indent: 20px;line-height:2;font-size: 15px" id="content">
        {{ article_instance.content | safe }}
    </div>

    <script>

    </script>
    <br><br><br>


    <!----------------------------------正文-----------end------------------------------>
     <!----------------------------------评论-----------start------------------------------>
    <div class="modal fade" id="mymodal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal"><span>&times;</span></button>
                    <h3 class="modal-title">回复</h3>
                </div>
                <div class="modal-body">
                    <div class="container-fluid">
                        {% for comment in article_comment %}
                            <p>{{ comment.author }}:{{ comment }}</p><hr>
                        {% endfor %}

                    </div>
                </div>
                <div class="modal-footer">
                    <div class="container-fluid">
                        <div class="form-group">
                            <form method="POST" action="/article/comments/{{ article_instance.id }}/">
                                {% csrf_token %}
                                <input type="hidden" name='blogerid' value="{{ user.id }}">
                                <input class="form-control" type="text" name="comment" placeholder="评论一下吧" >

                                <hr>

                                <span class="input-group-btn">
                                    <input type="submit" value="提交" class="form-control btn-success">
                                </span>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!----------------------------------评论-----------end------------------------------>
</div>
    <!----------------------------------script-----------start------------------------------>
<script>

    $(document).ready(function () {
        //点赞功能
        $('#li_btn').click(function () {
            $.get('/articles/likes/{{ article_instance.id }}/',function (data) {
                console.log(data);
                $('#li_sum').text('热度：'+data);
                $('#li_btn').addClass('disabled');
            });
        });
    });
</script>

{% endblock %}

<!--右侧模块-------------------------------------------------------------------------------->

{% block article_ins-20 %}
<div class="container-fluid">
    <div class="dropdown" style="margin-top: 75px">
        <button class="btn btn-default btn-block dropdown-toggle" data-toggle="dropdown">
            作者：{{ article_user.username }}
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu list-group" >
{#            <li class="list-group-item text-center list-group-item-text list-group-item-success">用户信息</li><hr>#}
{#            <li class="list-group-item">用户名：{{ article_user.username }}</li>#}
            <li class="list-group-item">年龄：{{ article_bloger.age }}</li>
            <li class="list-group-item">性别：{{ article_bloger.gender }}</li>
            <li class="list-group-item">地址:{{ article_bloger.address}}</li>
    </ul>
    </div>


</div>


{% endblock %}

zxsite/bodypage/templates/bodypage/article_manage.html
{% extends 'bodypage/base-s1.html' %}

{% block article-manage-20 %}
<div class="container-fluid" style="margin-top: 20px">
    <!----------------------------------左侧管理标签项-----------start------------------------------>
        <a href="/user/article-manage/newarticle/{{ user.id }}"><button class="btn btn-default btn-block ">写文章</button></a>

        <hr>

        <a href="/user/article-manage/{{ user.id }}"><button class="btn btn-success btn-block">管理已发布文章</button></a>

        <hr>

        <a href="/user/article-manage/draftarticle/{{ user.id }}"><button class="btn btn-block btn-default">草稿</button></a>

        <hr>

        <a href="/user/article-manage/delete/{{ user.id }}"><button class="btn btn-block btn-default">回收站</button></a>
    <!----------------------------------左侧管理标签项-----------end------------------------------>
</div>
{% endblock %}

<!--右侧模块------------------------------------------------------------------------------------->



{% block article-manage-80 %}
<div class="container-fluid" style="margin-top: 20px">
    <!----------------------------------右侧文章列表-----------start------------------------------>
    {% for article in user_article_P %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <a href="/article/{{ article.id }}"><h4>{{ article.title }}</h4></a>
            <div style="float: right;margin-right: 50px">
                <form method="post" action="/user/delete-article/{{ article.id }}">
                    {% csrf_token %}
                    <input type="hidden" name="user_id" value="{{ user.id }}">
                    <input type="submit" value="删除" class="btn btn-danger btn-sm" style="margin-top: -60px">
                </form>
            </div>
            <div style="float: right;margin-right: 20px">
                <a href="/user/article-manage/edit/{{ article.id }}"><button class="btn btn-sm btn-success" style="margin-top: -60px">
                    编辑文章
                </button></a>
            </div>
        </div>
        <div class="panel-body">
        {% comment %}<p>创建于：{{ article.created_time }}
        |作者：{{ article.author }}
        |浏览量：{{ article.views }}
        |热度：{{ article.likes }}
        </p>{% endcomment %}
        <p >{{ article.abstract }}</p>
        </div>
</div>
    {% endfor %}
    <!----------------------------------右侧文章列表-----------start------------------------------>

</div>


{% endblock %}

zxsite/bodypage/templates/bodypage/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'bodypage/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bodypage/wangEditor/dist/css/wangEditor.min.css' %}">
    <script src="{% static 'bodypage/js/jquery-3.1.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'bodypage/wangEditor/dist/js/wangEditor.min.js' %}"></script>
    <script src="{% static 'bodypage/js/bootstrap.js' %}"></script>



</head>
<body >
    <!--顶栏条div-------------------------------------------start--------------------------------------->
    <nav class="navbar navbar-default">
        <div class="container-fluid">
        <!--添加登录注册等项目--------------------------------------------------------------------------->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <div class="nav navbar-nav navbar-left">
                  <a href="/index"><button type="button" class="btn btn-success navbar-btn">首页</button></a>
                </div>
                {% if not user.is_authenticated %}
                    <div class="nav navbar-nav navbar-right">
                        <a href="/register"><button type="button" class="btn btn-default navbar-btn">注册</button></a>
                        <a href="/login"><button type="button" class="btn btn-default navbar-btn">登录</button></a>
                    </div>
                {% else %}
                    <div class="nav navbar-nav navbar-right">
                        <a href="/user/{{ user.id }}"><button type="button" class="btn btn-default navbar-btn">
                            {{ user.username }}</button></a>
                        <a href="{% url 'bodypage:logout' %}"><button type="button" class="btn btn-default navbar-btn">
                            注销</button></a>
                    </div>
                {% endif %}
            </div>
        <!--添加登录注册等项目---------------------------------end------------------------------------------>
        </div>
    </nav>
    <!--顶栏条div-------------------------------------------end--------------------------------------->
    {% block style-20-80 %}{% endblock %}
    {% block style-10-70-10 %}{% endblock %}
    {% block testpage %}{% endblock %}


    <br><br><br>

    <footer class="footer" style="background-color: #e7e7e7;height:50px;">
        <div class="container" style="padding-top: 10px">
            <p class="text-muted">welcome to my webpage</p>
        </div>
    </footer>


</body>
</html>

zxsite/bodypage/templates/bodypage/user.html
{% extends 'bodypage/base-s1.html' %}

{% block user-20 %}
    <!--用户信息--------------------------------start--------------------------------------->
    <div class="container-fluid">
        <ul class="list-group" style="margin-top: 20px">
            <li class="list-group-item text-center list-group-item-text">用户信息</li><hr>
            <li class="list-group-item">
            <span style="margin-right: 10px">
                 <img src="{{ user_info_profile.portrait.url }}  " alt="" style="width: 35px">
            </span>
                用户名：{{ user_info.username }}
            <span>
                <div class="btn">
                    {% if user.id == user_info.id or user_info_profile in user.bloger.likelist.all %}
                        <button class="btn btn-default btn-sm" disabled>已关注</button>
                    {% else %}
                    <form method="post" action="/user/addlikes/{{user.id }}">
                        {% csrf_token %}
                        <input type="hidden" name="userid" value="{{ user_info.id }}">
                        <input type="submit" value="关注 " class="btn btn-default">
                    </form>
                    {% endif %}
                </div>
            </span>

            </li>
            <li class="list-group-item">年龄：{{ user_info_profile.age }}</li>
            <li class="list-group-item">性别：{{ user_info_profile.gender }}</li>
            <li class="list-group-item">签名：{{ user_info_profile.signiture }}</li>
            <li class="list-group-item">地址:{{ user_info_profile.address}}</li>
        </ul>


    <!--用户信息--------------------------------start--------------------------------------->


    <!--用户设置选项--------------------------------start------------------------------------->
        {% if user.id == current_userid %}
            <div class="">
                <a href="{% url 'bodypage:edit_user_info' user.id %}"><button class="btn btn-success btn-block">编辑个人信息</button></a>
                <br>
                <a href="{% url 'bodypage:article_manage' user.id %}"><button class="btn btn-success btn-block">管理文章</button></a>
            </div>
        {% endif %}
        <br>
        <!--用户设置选项--------------------------------end------------------------------------->
        <!--用户关注--------------------------------start------------------------------------->
        <div>
            <button for="" class="btn btn-default btn-block disabled">用户关注：</button>

            <br>

            <div class="btn-group">
                {% for userins in user_info_profile.likelist.all %}
                    <a href="/user/{{ userins.user.id }}"><button class="btn btn-default">{{ userins }}</button> </a>
                {% endfor %}
            </div>
        </div>

        <hr>

        <div>
            <button for="" class="btn btn-default btn-block disabled">用户被关注：</button>

            <br>

            <div class="btn-group">
                {% for userins in user_info_profile.re_likelists.all %}
                    <a href="/user/{{ userins.user.id }}"><button class="btn btn-default">{{ userins }}</button></a>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

<!--右侧模块-------------------------------------------------------------------------------->

{% block user-80 %}
    <!---显示文章-------------------------------------------------------->
    {% for article in user_article %}
    <ul class="list-group" style="margin-top: 20px">
            <li class="list-group-item h3 ">
                <a href="/article/{{ article.id }}">{{ article.title }}</a>
            </li>
            <li class="list-group-item">
                <span class="">摘要：</span>{{ article.abstract }}
            </li>
            <li class="list-group-item">
                创建于：{{ article.created_time }}
                |作者：{{ article.author }}
                |浏览量：{{ article.views }}
                |热度：{{ article.likes }}
            </li>
    </ul>
    {% endfor %}
    <!---------------显示翻页---------------------------------------->
    <nav aria-label="page navigation">
        <ul class="pagination ">
            <li>
            {% if user_article.has_previous %}
                <a href="?page={{ user_article.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
             {% endif %}
            </li>
            {% for i in user_article.paginator.page_range %}
            <li>
               <a href="?page={{ i }}">
                    <span aria-hidden="true">{{ i }}</span>
                </a>
            </li>
            {% endfor %}
            <li>
            {% if user_article.has_next %}
                <a href="?page={{ user_article.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            {% endif %}
            </li>
        </ul>
    </nav>

{% endblock %}